const Orders = [
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Delivered",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Delivered",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Delivered",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Delivered",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Pending",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
  {
    productName: "Potato",
    productNumber: "8223",
    paymentStatus: "Due",
    shipping: "Declined",
  },
];
